blockExoticSubdeps: true
catalogMode: prefer
cleanupUnusedCatalogs: true
minimumReleaseAge: 2880
shellEmulator: true

trustPolicy: no-downgrade

packages:
  - docs/
  - examples/*
  - packages/**

catalog:
  '@antfu/eslint-config': 7.2.0
  '@clack/prompts': 1.0.0
  '@parcel/watcher': 2.5.6
  '@types/node': 25.0.9
  '@vue/tsconfig': 0.8.1
  c12: 3.3.3
  citty: 0.2.0
  consola: 3.4.2
  discord.js: 14.25.1
  eslint: 9.39.2
  eslint-plugin-format: 1.3.1
  exsolve: 1.0.8
  husky: 9.1.7
  rimraf: 6.1.2
  rolldown: 1.0.0-rc.2
  scule: 1.3.0
  tsdown: 0.20.1
  typescript: 5.9.3
  vitepress: 1.6.4
  vitest: 4.0.18
  vue: 3.5.27

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - bufferutil
  - esbuild
  - utf-8-validate
  - zlib-sync

verifyDepsBeforeRun: install
