packages:
  - packages/**
  - examples/*
  - docs/

catalog:
  '@antfu/eslint-config': ^6.2.0
  '@types/node': ^24.10.1
  '@vue/tsconfig': ^0.8.1
  c12: ^3.3.2
  citty: ^0.1.6
  consola: ^3.4.2
  discord.js: ^14.24.2
  eslint: ^9.39.1
  eslint-plugin-format: ^1.0.2
  husky: ^9.1.7
  rimraf: ^6.1.0
  scule: ^1.3.0
  tsdown: ^0.16.5
  typescript: ~5.9.3
  vitepress: ^1.6.4
  vitest: ^4.0.10
  vue: ^3.5.24

catalogMode: strict

ignoredBuiltDependencies:
  - bufferutil
  - esbuild
  - utf-8-validate
  - zlib-sync

shellEmulator: true
