name: Deploy Docs
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: [docs/**/*.*, .github/workflows/deploy-docs.yml]

defaults:
  run:
    working-directory: ./docs

concurrency:
  group: pages
  cancel-in-progress: true

env:
  DO_NOT_TRACK: 1
  VOLTA_FEATURE_PNPM: 1

jobs:
  deploy:
    name: Build & Deploy Docs
    timeout-minutes: 10
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # We need all history for doc edit dates
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0

      - name: Cache dependencies
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        with:
          path: ~/.local/share/pnpm/store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Setup node
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151

      - name: Install dependencies
        run: pnpm install --filter=docs --frozen-lockfile --ignore-scripts

      - name: Build docs
        run: pnpm run docs:build

      - name: Configure gh pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d

      - name: Upload artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b
        with:
          path: docs/.vitepress/dist

      - name: Deploy page
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128
